# Generated by Django 3.2.7 on 2021-10-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='max_bluepoint',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
