# Generated by Django 3.2.7 on 2021-10-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbooks', '0003_alter_bluepoint_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='bluepoint',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
