# Generated by Django 3.2.7 on 2021-10-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbooks', '0005_remove_bluepoint_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bluepoint',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
