# Generated by Django 3.2.7 on 2021-10-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbooks', '0008_auto_20211022_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='bluepoint',
            name='sort_grade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
