# Generated by Django 3.2.7 on 2021-10-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbooks', '0009_bluepoint_sort_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bluepoint',
            name='crag_name',
        ),
        migrations.AddField(
            model_name='bluepoint',
            name='climber',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
