# Generated by Django 3.2.7 on 2021-10-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbooks', '0010_auto_20211029_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='bluepoint',
            name='max_bluepoint',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
