# Generated by Django 3.2.7 on 2021-10-29 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbooks', '0011_bluepoint_max_bluepoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bluepoint',
            name='max_bluepoint',
        ),
    ]
